[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0"
tokio-stream = "0"
futures = "0"
async-recursion = "1"
trait-variant = "0"
async-trait = "0"
anyhow = "1"
tracing = "0"
tracing-subscriber = { version = "0", features = ["fmt", "time"] }
time = "0"
